apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-ingress-service-monitor
spec:
  jobLabel: nginx-ingress
  selector:
    matchLabels:
      app: nginx-ingress
      release: {{.Release.name}}
  namespaceSelector:
    matchNames:
      - {{.Release.Namespace}}
  endpoints:
    - port: metrics
      interval: 30s