nginx-ingress:
  controller:
    stats:
      enabled: true
    metrics:
      enabled: true
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    service:
      targetPorts:
        http: http
        https: http
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:033387483587:certificate/c48c304e-7cf5-414f-855e-2b53f46eec5b
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
        service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'
arn:  arn:aws:acm:us-east-1:033387483587:certificate/c48c304e-7cf5-414f-855e-2b53f46eec5b
